### ISSUE TITLE
Constants file 

### ISSUE THREAD

**Issue by vamshikrishnajr** [cotterapp/python-sdk#1]
I was trying to do this

> response = cotter.login_with_phone_otp(api_key, port)

got this error

> Traceback (most recent call last):
>   File "scripts/2021.04_add_public_directory_docs.py", line 5, in <module>
>     response = cotter.login_with_email_link(api_key, port)
>   File "/home/vamshi/omrx/env/lib/python3.8/site-packages/cotter/__init__.py", line 135, in login_with_email_link
>     return login(api_key, port, "EMAIL", "MAGIC_LINK")
>   File "/home/vamshi/omrx/env/lib/python3.8/site-packages/cotter/__init__.py", line 106, in login
>     url = constants.CotterJSURL + "/app"
> NameError: name 'constants' is not defined

**Comment by albertpurnama** [comment]
Hi @vamshikrishnajr what python version are you using ?

**Comment by vamshikrishnajr** [comment]
Hi,

I'm using python 3.8.5 and cotter 0.0.6

**Comment by vamshikrishnajr** [comment]
I tried substituting the constants.CotterJSURL with original value from constants.py, it worked but I think that's not the complete solution.

**Comment by widnyana** [comment]
Hi @albertputrapurnama, I made a pull request for this issue.

please kindly review :)
